import { motion } from "motion/react";
import { useEffect } from "react";

export function PrivacyPolicy() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-[#171614] text-white pt-32 pb-20 font-['Montserrat']">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="container mx-auto px-4 max-w-4xl"
      >
        <h1 className="text-4xl md:text-5xl font-['MADE_Soulmaze'] uppercase tracking-tighter mb-4">
          Privacy Policy
        </h1>
        <p className="text-slate-400 italic mb-12 border-b border-[#ADB9FF]/20 pb-6 text-sm">
          This privacy policy is a translated version of the original German text. In case of discrepancies, the German version shall prevail.
        </p>

        <div className="space-y-12 text-slate-300 leading-relaxed text-sm md:text-base">
          
          {/* SECTION 1 */}
          <section className="space-y-6">
            <h2 className="text-[#ADB9FF] font-semibold uppercase tracking-widest text-lg border-b border-[#ADB9FF]/10 pb-2">
              1. Data Protection at a Glance
            </h2>
            
            <div>
              <h3 className="text-white font-medium mb-2 text-lg">General Information</h3>
              <p className="mb-4">The following information provides a simple overview of what happens to your personal data when you visit this website. Personal data is any data that can be used to personally identify you. Detailed information on data protection can be found in our privacy policy listed below.</p>
            </div>

            <div>
              <h3 className="text-white font-medium mb-2 text-lg">Data Collection on this Website</h3>
              <p className="mb-2"><strong className="text-white">Who is responsible for data collection on this website?</strong><br/>
              Data processing on this website is carried out by the website operator. You can find their contact details in the section "Information on the responsible body".</p>
              
              <p className="mb-2"><strong className="text-white">How do we collect your data?</strong><br/>
              On the one hand, your data is collected when you provide it to us. This could include, for example, data that you enter into a contact form. Other data is collected automatically or with your consent by our IT systems when you visit the website. This is primarily technical data (e.g., internet browser, operating system, or time of page access). This data is collected automatically as soon as you access this website.</p>
              
              <p className="mb-2"><strong className="text-white">What do we use your data for?</strong><br/>
              Some of the data is collected to ensure the website functions correctly. Other data may be used to analyze your user behavior. If contracts can be concluded or initiated via the website, the transmitted data will also be processed for contract offers, orders, or other order inquiries.</p>
              
              <p><strong className="text-white">What rights do you have regarding your data?</strong><br/>
              You have the right to receive information free of charge at any time about the origin, recipients, and purpose of your stored personal data. You also have the right to request the correction or deletion of this data. If you have given your consent to data processing, you can revoke this consent at any time for the future. Furthermore, you have the right, under certain circumstances, to request the restriction of the processing of your personal data. Furthermore, you have the right to lodge a complaint with the competent supervisory authority.</p>
            </div>
          </section>

          {/* SECTION 2 */}
          <section className="space-y-6">
            <h2 className="text-[#ADB9FF] font-semibold uppercase tracking-widest text-lg border-b border-[#ADB9FF]/10 pb-2">
              2. Hosting
            </h2>
            <p>We host the content of our website with the following provider: <strong>GitHub</strong></p>
            
            <div>
              <h3 className="text-white font-medium mb-2 text-lg">External Hosting</h3>
              <p className="mb-4">This website is hosted externally. The personal data collected on this website is stored on the servers of the host(s). This may include, in particular, IP addresses, contact requests, metadata and communication data, contract data, contact information, names, website access data, and other data generated by a website.</p>
              <p className="mb-4">External hosting is carried out for the purpose of fulfilling our contractual obligations to our potential and existing customers (Art. 6 para. 1 lit. b GDPR) and in the interest of a secure, fast, and efficient provision of our online services by a professional provider (Art. 6 para. 1 lit. f GDPR). If corresponding consent has been requested, processing is carried out exclusively on the basis of Art. 6 para. 1 lit. a GDPR and Section 25(1) TDDDG, insofar as consent includes the storage of cookies or access to information on the user's device within the meaning of the TDDDG. Consent can be withdrawn at any time.</p>
              <p className="mb-4">Our hosting provider(s) will process your data only to the extent necessary to fulfill its contractual obligations and in accordance with our instructions regarding this data.</p>
              <div className="bg-[#222225] p-6 rounded-xl border border-white/5 mt-4">
                <strong className="text-white block mb-2">We use the following hosting provider:</strong>
                GitHub, Inc.<br/>
                88 Colin P. Kelly Jr. Street<br/>
                San Francisco, CA 94107<br/>
                United States
              </div>
            </div>
          </section>

          {/* SECTION 3 */}
          <section className="space-y-6">
            <h2 className="text-[#ADB9FF] font-semibold uppercase tracking-widest text-lg border-b border-[#ADB9FF]/10 pb-2">
              3. General Information and Mandatory Disclosures
            </h2>
            
            <div>
              <h3 className="text-white font-medium mb-2 text-lg">Data Protection</h3>
              <p className="mb-4">The operators of this website take the protection of your personal data very seriously. We treat your personal data confidentially and in accordance with the statutory data protection regulations and this privacy policy.</p>
              <p className="mb-4">When you use this website, various personal data are collected. Personal data is data that can be used to personally identify you. This privacy policy explains what data we collect and what we use it for. It also explains how and for what purpose this happens.</p>
              <p className="text-amber-200/80 text-sm">Please note that data transmission over the Internet (e.g., when communicating via email) can have security vulnerabilities. Complete protection of data against access by third parties is not possible.</p>
            </div>

           <div className="bg-[#5367df]/10 border-l-4 border-[#5367df] p-6 rounded-r-xl my-6">
              <h3 className="text-white font-medium mb-3 text-lg">Information on the responsible body</h3>
              <p className="mb-4 text-sm">The responsible body for data processing on this website is:</p>
              <p className="text-white">
                Tran An Brandl<br/>
                Berliner Allee 134<br/>
                13088 Berlin, Germany<br/>
                Email: trananbrandl@gmail.com<br/>
                Phone: +49 176 81103145
              </p>
              <p className="mt-4 text-sm text-slate-300">The controller is the natural or legal person who, alone or jointly with others, decides on the purposes and means of processing personal data (e.g., names, email addresses, etc.).</p>
            </div>

            <div>
               <h3 className="text-white font-medium mb-2 text-lg">Data Retention Period</h3>
               <p>Unless a more specific retention period is stated within this privacy policy, your personal data will remain with us until the purpose for data processing no longer applies. If you assert a legitimate request for erasure or withdraw your consent to data processing, your data will be erased, provided we have no other legally permissible grounds for storing your personal data (e.g., tax or commercial law retention periods); in the latter case, erasure will occur after these grounds cease to apply.</p>
            </div>

            <div className="space-y-4">
               <h3 className="text-white font-medium text-lg">Legal Basis & Your Rights</h3>
               
               <p><strong className="text-white">Revocation of your consent to data processing:</strong> Many data processing operations are only possible with your express consent. You can revoke your consent at any time. The lawfulness of data processing carried out before the withdrawal remains unaffected.</p>
               
               <div className="border border-red-500/30 bg-red-500/5 p-5 rounded-lg">
                  <strong className="text-red-200 block mb-2 uppercase text-sm tracking-wider">Right to object to data processing in special cases and to direct marketing (Art. 21 GDPR)</strong>
                  <p className="text-sm">If data processing is based on Article 6(1)(e) or (f) GDPR, you have the right to object, on grounds relating to your particular situation, to the processing of your personal data at any time; this also applies to profiling based on these provisions. If you object, we will no longer process your personal data unless we can demonstrate compelling legitimate grounds for the processing which override your interests, rights, and freedoms, or the processing serves the purpose of establishing, exercising, or defending legal claims.</p>
               </div>

               <p><strong className="text-white">Right to lodge a complaint:</strong> In the event of violations of the GDPR, data subjects have the right to lodge a complaint with a supervisory authority.</p>
               <p><strong className="text-white">Right to data portability:</strong> You have the right to receive the data that we process automatically based on your consent or in fulfillment of a contract, in a commonly used, machine-readable format.</p>
               <p><strong className="text-white">Access, Correction and Deletion:</strong> Under the applicable legal provisions, you have the right at any time to free information about your stored personal data, its origin and recipients, and the purpose of the data processing, and a right to correction or deletion of this data.</p>
            </div>
          </section>

          {/* SECTION 4 */}
          <section className="space-y-6">
            <h2 className="text-[#ADB9FF] font-semibold uppercase tracking-widest text-lg border-b border-[#ADB9FF]/10 pb-2">
              4. Data Collection on this Website
            </h2>
            <div>
              <h3 className="text-white font-medium mb-2 text-lg">Inquiry via Email, Telephone, or Fax</h3>
              <p className="mb-4">When you contact us via email, telephone, or fax, your inquiry, including all resulting personal data (name, inquiry), will be stored and processed by us for the purpose of handling your request. We will not share this data without your consent.</p>
              <p>The processing of this data is based on Article 6(1)(b) GDPR, insofar as your request is related to the performance of a contract or is necessary for the implementation of pre-contractual measures. The data you send us via contact requests will remain with us until you request its deletion, revoke your consent to its storage, or the purpose for data storage no longer applies.</p>
            </div>
          </section>

          {/* SECTION 5 */}
          <section className="space-y-6">
            <h2 className="text-[#ADB9FF] font-semibold uppercase tracking-widest text-lg border-b border-[#ADB9FF]/10 pb-2">
              5. Plugins and Tools
            </h2>
            <div>
              <h3 className="text-white font-medium mb-2 text-lg">Google Fonts</h3>
              <p className="mb-4">This website uses Google Fonts, provided by Google, for the consistent display of fonts. When you visit a page, your browser loads the necessary fonts into its browser cache to display text and fonts correctly. For this purpose, the browser you are using must connect to Google's servers. This allows Google to know that this website was accessed via your IP address.</p>
              <p className="mb-4">The use of Google Fonts is based on Art. 6 para. 1 lit. f GDPR. The website operator has a legitimate interest in the uniform presentation of the typeface on its website.</p>
              <p>Further information about Google Fonts can be found at <a href="https://developers.google.com/fonts/faq" target="_blank" rel="noreferrer" className="text-[#ADB9FF] hover:underline">developers.google.com/fonts/faq</a> and in Google's privacy policy: <a href="https://policies.google.com/privacy?hl=en" target="_blank" rel="noreferrer" className="text-[#ADB9FF] hover:underline">policies.google.com/privacy</a>.</p>
              <p className="mt-6 text-xs text-slate-500 uppercase tracking-widest">Source: e-recht24.de</p>
            </div>
          </section>

        </div>
      </motion.div>
    </div>
  );
}